import type { Metadata } from "next";
import "./globals.css";
import { ReactFigmaProvider } from "@/app/polipo-react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactFigmaProvider>{children}</ReactFigmaProvider>
      </body>
    </html>
  );
}
